# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsrqVIrCdcwfL-P7vkNP0jHq2f4ueavx
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# from PIL import Image
# import tensorflow as tf
# 
# # Load saved model (replace path with your best model)
# # Example: tf.keras.models.save_model(resnet_model, "best_model.h5") earlier
# model = tf.keras.models.load_model("best_model.h5")
# 
# class_names = ["Covid", "Normal", "Viral Pneumonia"]  # adjust to your label_encoder.classes_
# 
# st.title("COVID-19 Detection from Chest X-ray")
# st.write("Upload a chest X-ray image to get a prediction.")
# 
# uploaded_file = st.file_uploader("Choose an X-ray image", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file is not None:
#     image = Image.open(uploaded_file).convert("RGB")
#     st.image(image, caption="Uploaded Image", use_column_width=True)
# 
#     # Preprocess
#     img_resized = image.resize((224, 224))
#     img_array = np.array(img_resized).astype("float32") / 255.0
#     img_array = np.expand_dims(img_array, axis=0)
# 
#     # Predict
#     preds = model.predict(img_array)
#     pred_class = np.argmax(preds, axis=1)[0]
#     confidence = np.max(preds)
# 
#     st.write(f"### Prediction: {class_names[pred_class]}")
#     st.write(f"Confidence: {confidence:.2f}")
#